# Generated by Django 4.2 on 2025-05-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Agendamento')),
                ('horario', models.CharField(max_length=5, verbose_name='Horário (HH:MM)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('A', 'Agendado'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'unique': 'Já existe um serviço com este nome.'}, max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('duracao', models.PositiveIntegerField(default=60, editable=False, verbose_name='Duração (minutos)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('ativo', models.BooleanField(default=True, help_text='Serviços inativos não aparecem para agendamento.')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios_disponiveis', models.JSONField(default=list, help_text='Lista de horários no formato ["08:00", "09:00", ...]')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
