# Generated by Django 4.2 on 2025-05-15 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo': 'A'}, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_profissional', to='agendamentos.profissional'),
        ),
        migrations.AddConstraint(
            model_name='profissional',
            constraint=models.UniqueConstraint(fields=('usuario', 'servico'), name='unique_profissional_servico'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'A')), fields=('profissional', 'data', 'horario'), name='unique_agendamento_profissional_horario'),
        ),
    ]
