# Generated by Django 5.2.1 on 2025-05-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_alter_agendamento_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Painel do Salão Link',
                'verbose_name_plural': '▶ Painel do Salão',
                'managed': False,
            },
        ),
    ]
