# Generated by Django 4.2 on 2025-05-15 19:11

from django.db import migrations

def populate_fields(apps, schema_editor):
    CustomUser = apps.get_model('usuarios', 'CustomUser')
    for user in CustomUser.objects.all():
        if not user.cpf:
            user.cpf = f'{user.id:011d}'[:11]  # Gera CPF temporário baseado no ID
        if not user.telefone:
            user.telefone = f'+55{user.id:011d}'[:15]  # Telefone temporário
        user.save()

class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0001_initial')
    ]

    operations = [
        migrations.RunPython(populate_fields),
    ]
